version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: hotel_mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: hotel_dev
    volumes:
      - mongodb_data:/data/db
    networks:
      - hotel-network

  redis:
    image: redis:7-alpine
    container_name: hotel_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - hotel-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hotel_backend
    restart: always
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://admin:password@mongodb:27017/hotel_dev?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - hotel-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hotel_frontend
    restart: always
    ports:
      - '3000:3000'
    environment:
      - VITE_API_URL=http://localhost:4000/api/v1
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - hotel-network

volumes:
  mongodb_data:
  redis_data:

networks:
  hotel-network:
    driver: bridge