services:
  - type: web
    name: hotel-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    autoDeploy: false
    
  - type: web
    name: hotel-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    autoDeploy: false